from . import start_handlers
from . import cart_handlers
from . import categories_handlers
from . import products_handlers
from . import callback
from . import auth_handlers
from . import orders_handlers
from . import feedback_handlers
from . import reviews_handlers
